import { Inter, Mulish } from "next/font/google";
import "./globals.css";
import ProviderSession from "./_components/ProviderSession";


const inter = Mulish({ subsets: ["latin"] });

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
 return (
  <html lang="en">
   <body className={`${inter.className}`}>
    <ProviderSession session={session}>
     {children}
    </ProviderSession>
   </body>
  </html>
 );
}
